image: python:3.4
services:
  - postgres:9.4
  - redis:2.8

stages:
  - test
  - release

variables:
  DJANGO_SETTINGS_MODULE: mailsend_tests.settings
  TEST_PG_USER: postgres
  TEST_PG_HOST: postgres
  TEST_PG_PASS: ""
  TEST_PG_NAME: mailsend
  TEST_PG_PORT: "5432"
  TEST_REDIS_HOST: redis
  TEST_REDIS_PORT: "6379"
  PACKAGECLOUD_REPO: oasiswork/crunchmail/python/

before_script:
  # make sure we can clone our private repos
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$CI_DEPLOY_PRIVATE_KEY")
  # cache python packages for faster builds
  - export PYTHONUSERBASE=/cache
  - export PYTHONPATH=/cache/lib/python3.4/site-packages:$PYTHONPATH
  - export PATH=/cache/bin:$PATH
  - pip install -U setuptools
  # Install mailsend
  # -e to enable developer mode and to have data files (like .yaml)
  - pip install -e  .[tests] --process-dependency-links

lint:
  stage: test
  script:
    - flake8

unittest:
  stage: test
  script:
    # Install munch
    - pip install --process-dependency-links git+ssh://git@git.owk.cc/crunchmail/munch.git@devel#egg=munch[tests]
    # Run tests
    - munch django test mailsend_tests

packagecloud-release:
  stage: release
  before_script:
    - apt-get update
    - apt-get install -y ruby
    - gem install package_cloud
  script:
    - python setup.py sdist
    - package_cloud push $PACKAGECLOUD_REPO dist/$CI_PROJECT_NAME-*.tar.gz
  only:
    - tags
