language: python
python:
  - "3.4"
services:
  - redis-server
addons:
  postgresql: "9.4"
env:
  DJANGO_SETTINGS_MODULE: munch_mailsend_tests.settings
  TEST_PG_USER: postgres
  TEST_PG_PASS: ""
  TEST_PG_NAME: munch
  TEST_PG_PORT: 5432
  TEST_REDIS_PORT: 6379
before_install:
  - export PYTHONUSERBASE=/cache
  - export PYTHONPATH=/cache/lib/python3.4/site-packages:$PYTHONPATH
  - export PATH=/cache/bin:$PATH
install:
  - pip install munch-core
  - pip install --process-dependency-links -e .[tests]
before_script:
  - flake8
script: munch django test munch_mailsend_tests
deploy:
  provider: pypi
  user: oasiswork-devs
  password:
    secure: "q9VCeOgnNtHcy5AqyAJIpQHqp0HrFMVKuzDShZMd/qmfDgE6UOnzj8JOQnVpxCBBOs6r716WYFUwVxW9pqnEe6xmjEDPhA66UMJymSdleUGiknSYw2m7Jk/4tzy63UCg9ZUDtvjLnPBjIZkUqFzYCAfzqkSS13yYY7v9z+eCXTixzV5KopNRO2de6q0uHAFXhxTO8r0l2Ja7MiAUDhyH76g1pWHWd8kKmTO57g1LFDjNJmrqXSpVBpl1XrjXuyxzI9pM5Q2IDgsBWMnNX4+IlzeUeYTxXm+9dP7Nd0OtaKPaTyur3IKqjh/O8UfOSU1Hkix6vfBpfj3dBY0Ed7HkH0EmK+ApbmGftGDb/qmF2l6L1BnG/Gk7Xpxska8HRcxUP/sc72fMVdYIA3IpccDe3PPY4/DGoiIymeyrqPfX/2qmXvY/BImwNiKao/B0S+YKwQBknPrNhNnF5DD6+0SP5dVlgB5FpqlRXVTPHCdMXKjxLKnc33p6yp5KoO4AzECz+C2Ld/9ctmy/TXQSRVrUaUryEDroAbVK+4SVxCQSNs2cyBrBiyt10GVrCRrlpTgqBmAdbzzXD8TgjpgXAsEJz/5ywvSwjZrU9fGondHve5B3ED+ZNAuL3B6BJbUcHWrVcr8CrNz2JsZwb6EuZjXrGdYQznTtfyEo0KOlvTjm8tc="
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: crunchmail/munch-mailsend
    branch: master
