language: python
python:
  - "3.4"
services:
  - redis-server
addons:
  postgresql: "9.4"
env:
  DJANGO_SETTINGS_MODULE: munch_mailsend_tests.settings
  TEST_PG_USER: postgres
  TEST_PG_PASS: ""
  TEST_PG_NAME: munch
  TEST_PG_PORT: 5432
  TEST_REDIS_PORT: 6379
before_install:
  - export PYTHONUSERBASE=/cache
  - export PYTHONPATH=/cache/lib/python3.4/site-packages:$PYTHONPATH
  - export PATH=/cache/bin:$PATH
install:
  - pip install git+https://github.com/crunchmail/munch-core.git@master
  - pip install --process-dependency-links -e .[tests]
before_script:
  - flake8
script: munch django test munch_mailsend_tests
